version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.springframework:spring-web
    versions:
    - 5.3.3
    - 5.3.4
    - 5.3.5
  - dependency-name: org.springframework:spring-jdbc
    versions:
    - 5.3.3
    - 5.3.4
    - 5.3.5
  - dependency-name: org.springframework:spring-core
    versions:
    - 5.3.3
    - 5.3.4
  - dependency-name: org.springframework:spring-context
    versions:
    - 5.3.3
    - 5.3.4
  - dependency-name: mysql:mysql-connector-java
    versions:
    - 8.0.23
  - dependency-name: org.apache.cxf:cxf-rt-frontend-jaxrs
    versions:
    - 3.4.2
